name: 'SyncAction'
description: 'GitHub Action which moves commits from one branch to another branch'
branding:
  icon: git-pull-request
  color: orange
author: mailz
inputs:
  GITHUB_TOKEN:
    description: "User token to be associated with this pull request."
    required: true
  BRANCH:
    description: "Branch to make the pull-request against"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
