name: 'SyncAction'
description: 'GitHub Action which syncs releases and develop branches'
branding:
  icon: git-pull-request
  color: orange
author: mailz
inputs:
  GITHUB_TOKEN:
    description: "User token to be associated with this pull request."
    required: true
  BRANCH:
    description: "Branch to make the pull-request against"
    required: true
  PR_TITLE:
    description: "What you would like as the title of the pull request. Default: 'sync: {FROM_BRANCH} to {TO_BRANCH}'"
    required: false
  PR_BODY:
    description: "What you would like in the body of the pull request. Default: 'New code has just landed in {fromBranch} so let's bring {toBranch} up to speed!'"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'